In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

LOAD IN DATA

In [2]:
df = pd.read_csv(r'C:\Users\JaceCordell\Desktop\lockheed_project\aviation_maintenance_dataset.csv', dtype= str)

print(f' Raw rows loaded:{len(df)}')

df.head()

 Raw rows loaded:1240

,maintenance_id,aircraft_id,aircraft_model,base_location,maintenance_type,supplier_name,event_date,downtime_hours,supplier_delay_days,maintenance_status,maintenance_cost,readiness_score
0,1,AC-1409,F-16,Luke AFB,Avionics,Northrop,11/23/2024,21.0,4,Completed,32772.26,71
1,2,AC-4811,B-2,Eglin AFB,Engine Repair,L3Harris,2024-02-17,30.0,4,Delayed,22190.36,64
2,3,AC-3615,C-130,Hill AFB,Hydraulics,Northrop,03/21/2025,30.0,8,Awaiting Parts,19366.31,57
3,4,AC-1711,C-130,Eglin AFB,Engine Repair,GE Aerospace,2024-11-05,22.0,3,In Progress,19411.24,74
4,5,AC-4733,F-16,Fort Worth,Avionics,Raytheon,01/24/2024,19.0,0,Delayed,4300.99,86

INITIAL DATA AUDIT

In [3]:
#How many rows and columns in the dataframe?
print('=== SHAPE ===')
print(f'Rows: {df.shape[0]} | Columns: {df.shape[1]}')

#How many NULL values in the dataframe (per column)?
print('\n=== NULL COUNTS ===')
print(df.isnull().sum())

#Find the total duplicates and
print('\n=== DUPLICATE ROWS ===')
print(f'Full duplicates: {df.duplicated().sum()}')
print(f'Duplicate maintenance_ids: {df.duplicated(subset=["maintenance_id"]).sum()}')

=== SHAPE ===
Rows: 1240 | Columns: 12

=== NULL COUNTS ===
maintenance_id          0
aircraft_id             0
aircraft_model          0
base_location           0
maintenance_type        0
supplier_name           0
event_date              0
downtime_hours         68
supplier_delay_days    80
maintenance_status      0
maintenance_cost        0
readiness_score         0
dtype: int64

=== DUPLICATE ROWS ===
Full duplicates: 40
Duplicate maintenance_ids: 40

REMOVE DUPLICATES

In [4]:
#How many duplicates?
df.duplicated().sum()

np.int64(40)

In [5]:
#Inspect duplicates
duplicates = df[df.duplicated()]
duplicates.head()

,maintenance_id,aircraft_id,aircraft_model,base_location,maintenance_type,supplier_name,event_date,downtime_hours,supplier_delay_days,maintenance_status,maintenance_cost,readiness_score
1200,1179,AC-6758,F-35A,Hill AFB,Electrical,GE Aerospace,09/12/2024,34.0,11,Completed,33147.36,55
1201,866,AC-5075,C-130,Nellis AFB,Software Update,Raytheon,04/22/2025,0.0,2,Delayed,27535.4,98
1202,102,AC-1502,F-35A,Eglin AFB,Avionics,GE Aerospace,03/13/2024,22.0,4,In Progress,26407.93,79
1203,440,AC-1107,F-22,Eglin AFB,Hydraulics,L3Harris,11/03/2024,15.0,2,Delayed,22756.34,87
1204,59,AC-7565,C-130,Fort Worth,Landing Gear,Raytheon,2025-02-24,20.0,8,Completed,25156.02,68

In [6]:
#Inspect duplicate maintenance ids
duplicates['maintenance_id'].head()

1200    1179
1201     866
1202     102
1203     440
1204      59
Name: maintenance_id, dtype: object

In [8]:
df.duplicated().sum()
df.shape

(1240, 12)

In [9]:
df = df.drop_duplicates()
df.duplicated().sum()
df.shape

(1200, 12)

ADDRESS THE NULL VALUES IN THE DATASET

In [10]:
#Display the unique values of the supplier delay days column
supplier_delay_values = df['supplier_delay_days'].unique()
print(supplier_delay_values)

['4' '8' '3' '0' '5' '2' '12' '7' '6' '9' '11' nan '10' '1' '14' '17' '15'
 '13' '16']

In [11]:
#Convert valid numeric values to numbers and nan to NaN to be handled
df['supplier_delay_days'] =pd.to_numeric(df['supplier_delay_days'], errors = 'coerce')
#print(df['supplier_delay_days'].median())

In [12]:
#Replace NULL values with the median of the supplier delay days column
df['supplier_delay_days'] = df['supplier_delay_days'].fillna(df['supplier_delay_days'].median())

In [13]:
#Check to see if NULL values have been filled
supplier_delay_values = df['supplier_delay_days'].unique()
print(supplier_delay_values)

[ 4.  8.  3.  0.  5.  2. 12.  7.  6.  9. 11. 10.  1. 14. 17. 15. 13. 16.]

In [14]:
#Repeat the process for the downtime hours column
downtime_hours_values = df['downtime_hours'].unique()
print(downtime_hours_values)

['21.0' '30.0' '22.0' '19.0' '13.0' '10.0' '16.0' '9.0' '17.0' '12.0'
 '20.0' '14.0' '26.0' '15.0' '8.0' '24.0' '18.0' '11.0' '6.0' nan '28.0'
 '7.0' '32.0' '23.0' '27.0' '29.0' '35.0' '34.0' '2.0' '33.0' '4.0' '25.0'
 '3.0' '0.0' '31.0' '38.0' '1.0' '36.0' '5.0' '37.0' '49.0']

In [15]:
df['downtime_hours'] = pd.to_numeric(df['downtime_hours'],errors = 'coerce')
df['downtime_hours'] = df['downtime_hours'].fillna(df['downtime_hours'].median())

In [16]:
downtime_hours_values = df['downtime_hours'].unique()
print(downtime_hours_values)

[21. 30. 22. 19. 13. 10. 16.  9. 17. 12. 20. 14. 26. 15.  8. 24. 18. 11.
  6. 28.  7. 32. 23. 27. 29. 35. 34.  2. 33.  4. 25.  3.  0. 31. 38.  1.
 36.  5. 37. 49.]

In [17]:
#Run a NULL check again
print('\n=== NULL COUNTS ===')
print(df.isnull().sum())

=== NULL COUNTS ===
maintenance_id         0
aircraft_id            0
aircraft_model         0
base_location          0
maintenance_type       0
supplier_name          0
event_date             0
downtime_hours         0
supplier_delay_days    0
maintenance_status     0
maintenance_cost       0
readiness_score        0
dtype: int64

NORMALIZE ALL THE DATES INTO THE SAME FORMAT (MM-DD-YYYY)

In [18]:
#df['event_date'] = pd.to_datetime(df['event_date'], errors = 'coerce')

In [19]:
df = df.copy()

In [20]:
#Convert all values in event date column to strings for parsing and normalization
df['event_date'] = df['event_date'].astype(str)

In [21]:
#Find all the YYYY-MM-DD dates in event date column
mask = df['event_date'].str.match(r'^\d{4}-\d{2}-\d{2}$')

#Convert these dates to MM-DD-YYYY and datetimes
df.loc[mask, 'event_date'] = pd.to_datetime(df.loc[mask, 'event_date'], format = '%Y-%m-%d').dt.strftime('%m-%d-%Y')

In [22]:
df.head()

,maintenance_id,aircraft_id,aircraft_model,base_location,maintenance_type,supplier_name,event_date,downtime_hours,supplier_delay_days,maintenance_status,maintenance_cost,readiness_score
0,1,AC-1409,F-16,Luke AFB,Avionics,Northrop,11/23/2024,21.0,4.0,Completed,32772.26,71
1,2,AC-4811,B-2,Eglin AFB,Engine Repair,L3Harris,02-17-2024,30.0,4.0,Delayed,22190.36,64
2,3,AC-3615,C-130,Hill AFB,Hydraulics,Northrop,03/21/2025,30.0,8.0,Awaiting Parts,19366.31,57
3,4,AC-1711,C-130,Eglin AFB,Engine Repair,GE Aerospace,11-05-2024,22.0,3.0,In Progress,19411.24,74
4,5,AC-4733,F-16,Fort Worth,Avionics,Raytheon,01/24/2024,19.0,0.0,Delayed,4300.99,86

In [23]:
#Replace all / with - in event date column
df['event_date'] = df['event_date'].str.replace('/','-')
df.head()

,maintenance_id,aircraft_id,aircraft_model,base_location,maintenance_type,supplier_name,event_date,downtime_hours,supplier_delay_days,maintenance_status,maintenance_cost,readiness_score
0,1,AC-1409,F-16,Luke AFB,Avionics,Northrop,11-23-2024,21.0,4.0,Completed,32772.26,71
1,2,AC-4811,B-2,Eglin AFB,Engine Repair,L3Harris,02-17-2024,30.0,4.0,Delayed,22190.36,64
2,3,AC-3615,C-130,Hill AFB,Hydraulics,Northrop,03-21-2025,30.0,8.0,Awaiting Parts,19366.31,57
3,4,AC-1711,C-130,Eglin AFB,Engine Repair,GE Aerospace,11-05-2024,22.0,3.0,In Progress,19411.24,74
4,5,AC-4733,F-16,Fort Worth,Avionics,Raytheon,01-24-2024,19.0,0.0,Delayed,4300.99,86

In [24]:
#Finally convert full event date column to datetimes
df['event_date'] = pd.to_datetime(df['event_date'], format = '%m-%d-%Y', errors='coerce')
#Verify the ype conversion
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       1200 non-null   object
 1   aircraft_id          1200 non-null   object
 2   aircraft_model       1200 non-null   object
 3   base_location        1200 non-null   object
 4   maintenance_type     1200 non-null   object
 5   supplier_name        1200 non-null   object
 6   event_date           1200 non-null   datetime64[ns]
 7   downtime_hours       1200 non-null   float64
 8   supplier_delay_days  1200 non-null   float64
 9   maintenance_status   1200 non-null   object
 10  maintenance_cost     1200 non-null   object
 11  readiness_score      1200 non-null   object
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 121.9+ KB

In [25]:
df.head()

,maintenance_id,aircraft_id,aircraft_model,base_location,maintenance_type,supplier_name,event_date,downtime_hours,supplier_delay_days,maintenance_status,maintenance_cost,readiness_score
0,1,AC-1409,F-16,Luke AFB,Avionics,Northrop,2024-11-23,21.0,4.0,Completed,32772.26,71
1,2,AC-4811,B-2,Eglin AFB,Engine Repair,L3Harris,2024-02-17,30.0,4.0,Delayed,22190.36,64
2,3,AC-3615,C-130,Hill AFB,Hydraulics,Northrop,2025-03-21,30.0,8.0,Awaiting Parts,19366.31,57
3,4,AC-1711,C-130,Eglin AFB,Engine Repair,GE Aerospace,2024-11-05,22.0,3.0,In Progress,19411.24,74
4,5,AC-4733,F-16,Fort Worth,Avionics,Raytheon,2024-01-24,19.0,0.0,Delayed,4300.99,86

In [26]:
#Verify no nulls
df.isnull().sum()

maintenance_id         0
aircraft_id            0
aircraft_model         0
base_location          0
maintenance_type       0
supplier_name          0
event_date             0
downtime_hours         0
supplier_delay_days    0
maintenance_status     0
maintenance_cost       0
readiness_score        0
dtype: int64

NORMALIZE EACH TEXT COLUMN WITH PROPER CAPITALIZATION

In [27]:
#Check unique values in aircraft model column
aircraft_model_values = df['aircraft_model'].unique()
print(aircraft_model_values)

['F-16' 'B-2' 'C-130' 'F-35A' 'F-22']

In [28]:
#Check unique values in base location column
base_location_values = df['base_location'].unique()
print(base_location_values)

['Luke AFB' 'Eglin AFB' 'Hill AFB' 'Fort Worth' 'Nellis AFB']

In [29]:
#Check unique values in maintenance type column
maintenance_type_values = df['maintenance_type'].unique()
print(maintenance_type_values)

['Avionics' 'Engine Repair' 'Hydraulics' 'Landing Gear' 'Software Update'
 'Electrical' 'engine repair' 'electrical' 'landing gear' 'hydraulics'
 'avionics' 'software update']

In [30]:
#Apply standard capitalization to maintenance column
df['maintenance_type'] = df['maintenance_type'].str.title()

In [31]:
#Check unique values in maintenance type column
maintenance_type_values = df['maintenance_type'].unique()
print(maintenance_type_values)

['Avionics' 'Engine Repair' 'Hydraulics' 'Landing Gear' 'Software Update'
 'Electrical']

In [32]:
#Check unique values in supplier name column
supplier_name_values = df['supplier_name'].unique()
print(supplier_name_values)

['Northrop' 'L3Harris' 'GE Aerospace' 'Raytheon' 'Boeing' 'Boeing '
 'GE Aerospace ' 'Raytheon ' 'L3Harris ' 'Northrop ']

In [33]:
#Remove the trailing spaces from the supplier name column
df['supplier_name'] = df['supplier_name'].str.strip()

In [34]:
supplier_name_values = df['supplier_name'].unique()
print(supplier_name_values)

['Northrop' 'L3Harris' 'GE Aerospace' 'Raytheon' 'Boeing']

In [35]:
#Check unique values in maintenance type column
maintenance_type_values = df['maintenance_type'].unique()
print(maintenance_type_values)

['Avionics' 'Engine Repair' 'Hydraulics' 'Landing Gear' 'Software Update'
 'Electrical']

DATA HAS BEEN CLEANED
NOW CREATE NEW COLUMNS FOR TABLEAU VISUALIZATION USE

In [36]:
#Create a month and year column
df['month'] = df['event_date'].dt.month
df['year'] = df['event_date'].dt.year

In [37]:
#Create a total delay column
df['total_delay'] = df['downtime_hours']+df['supplier_delay_days']

In [38]:
#Convert readiness score to numeric then Create a risk category column
df['readiness_score'] = pd.to_numeric(df['readiness_score'])
df['risk_level'] = np.where(df['readiness_score']<70,'High Risk', 'Normal')

INITIAL ANALYSIS

In [39]:
#Average down time by aircraft
df.groupby('aircraft_model')['downtime_hours'].mean()

aircraft_model
B-2      17.750000
C-130    17.554348
F-16     18.175214
F-22     17.705882
F-35A    17.817352
Name: downtime_hours, dtype: float64

In [40]:
#Highest Supplier Delays
df.groupby('supplier_name')['supplier_delay_days'].mean().sort_values(ascending=False)

supplier_name
GE Aerospace    4.984674
Raytheon        4.702703
Northrop        4.559055
L3Harris        4.547414
Boeing          4.476190
Name: supplier_delay_days, dtype: float64

In [41]:
#Maintenance Type with Highest down times
df.groupby('maintenance_type')['downtime_hours'].mean().sort_values(ascending=False)

maintenance_type
Hydraulics         18.635514
Electrical         18.130653
Engine Repair      17.943662
Landing Gear       17.911602
Avionics           17.145000
Software Update    16.891192
Name: downtime_hours, dtype: float64

ROOT CAUSE ANALYSIS

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       1200 non-null   object
 1   aircraft_id          1200 non-null   object
 2   aircraft_model       1200 non-null   object
 3   base_location        1200 non-null   object
 4   maintenance_type     1200 non-null   object
 5   supplier_name        1200 non-null   object
 6   event_date           1200 non-null   datetime64[ns]
 7   downtime_hours       1200 non-null   float64
 8   supplier_delay_days  1200 non-null   float64
 9   maintenance_status   1200 non-null   object
 10  maintenance_cost     1200 non-null   object
 11  readiness_score      1200 non-null   int64
 12  month                1200 non-null   int32
 13  year                 1200 non-null   int32
 14  total_delay          1200 non-null   float64
 15  risk_level           1200 non-null   object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(9)
memory usage: 150.0+ KB

In [43]:
#Convert maintenance cost column from string to numeric
df['maintenance_cost'] = pd.to_numeric(df['maintenance_cost'])

KPI ANALYSIS

In [46]:
#Get the mean of the down time hours and maintenance cost columns as well as count of the maintenance ids
#Grouped by maintenance type
#Rounded to 2 decimal places
df.groupby('maintenance_type').agg({
    'downtime_hours':'mean', 
    'maintenance_cost':'mean', 
    'maintenance_id':'count'
}).round(2).sort_values(by='downtime_hours', ascending = False)

                  downtime_hours  maintenance_cost  maintenance_id
maintenance_type
Hydraulics                 18.64          25813.99             214
Electrical                 18.13          27147.95             199
Engine Repair              17.94          24124.42             213
Landing Gear               17.91          27297.53             181
Avionics                   17.14          25259.74             200
Software Update            16.89          25789.76             193

In [52]:
#Export cleaned dataset to a csv
df.to_csv("aviation_maintenance_cleaned.csv", index = False)

In [64]:
#Export cleaned dataset to a csv
df.to_csv(r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\aviation_maintenance_cleaned_csv.csv", index = False)

In [51]:
import os

os.getcwd()

'C:\\Users\\JaceCordell\\lockheed_project'

In [62]:
from datetime import datetime
df['event_date'] = df['event_date'].dt.strftime("%Y%m%d")

AttributeError: Can only use .dt accessor with datetimelike values